In [8]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
###
# Array Manipulation and Processing
###
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [10]:
print(arr.shape)
print(arr.ndim)

(5,)
1


In [13]:
np.sum(arr)

np.int64(15)

In [14]:
np.mean(arr)

np.float64(3.0)

In [15]:
np.median(arr)

np.float64(3.0)

In [16]:
np.max(arr)

np.int64(5)

In [17]:
np.min(arr)

np.int64(1)

In [18]:
## array Manipulation
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [19]:
# Create a 2D array
arr3 = np.array([[1, 2], [3, 4], [5, 6]])
print(arr3)

[[1 2]
 [3 4]
 [5 6]]


In [22]:
#reshape
arr4 = arr3.reshape(2, 3)
print(arr4)

[[1 2 3]
 [4 5 6]]


In [23]:
arr5 =arr2.reshape(3, 2)
print(arr5)

[[1 2]
 [3 4]
 [5 6]]


In [24]:
###
# Mathematical Operations and functions
###
number = np.array([1, 10, 20, 4, 5])
np.sort(number)    

array([ 1,  4,  5, 10, 20])

In [27]:
np.add(120, 20)
np.multiply(100, 20)

np.int64(2000)

In [ ]:
###
#Linear Algebra
###

np.dot
np.linalg.inv


In [74]:
###
# Radom number Generation
###

guess = np.random.random_integers(0,10)
print(guess)

1


C:\Users\cheko\AppData\Local\Temp\ipykernel_23696\2083509982.py:5: DeprecationWarning: This function is deprecated. Please call randint(0, 10 + 1) instead
  guess = np.random.random_integers(0,10)
